version: "3.3"

services:
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: starcoex
      WORDPRESS_DB_PASSWORD: Coex2023^^
      WORDPRESS_DB_NAME: starcoexdb
    volumes:
      - ./wp-content:/var/www/html/wp-content

  db:
    image: mysql:latest
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    environment:
      MYSQL_DATABASE: starcoexdb
      MYSQL_USER: starcoex
      MYSQL_PASSWORD: Coex2023^^
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
# ---
# version: "3.1"

# services:
#   wordpress:
#     image: wordpress

#     restart: always

#     ports:
#       - 8080:80

#     environment:
#       WORDPRESS_DB_HOST: db

#       WORDPRESS_DB_USER: exampleuser

#       WORDPRESS_DB_PASSWORD: examplepass

#       WORDPRESS_DB_NAME: exampledb

#     volumes:
#       - wordpress:/var/www/html

#   db:
#     image: mysql:5.7

#     restart: always

#     environment:
#       MYSQL_DATABASE: exampledb

#       MYSQL_USER: exampleuser

#       MYSQL_PASSWORD: examplepass

#       MYSQL_RANDOM_ROOT_PASSWORD: "1"

#     volumes:
#       - db:/var/lib/mysql

# volumes:
#   wordpress:

#   db:
